### ISSUE TITLE
Query metadata (size and modified time) on MTP files?

### ISSUE THREAD

**Issue by tlokovic** [daladim/winmtp#2]
Hi, I have some file syncing code in Rust that currently only works with the local filesystem, but I'd like to add support for MTP devices and your library seems like a great candidate for that.  My syncing code requires traversing to compare directory hierarchies and then copying files based on differences, all of which your library seems to support nicely.  But it also requires getting the file size and modified timestamp of files to decide which need to be transferred and which don't.  On the local filesystem I get this metadata from std::fs::Metadata (https://doc.rust-lang.org/std/fs/struct.Metadata.html).  I don't see a way with your library to get that info from files on a MTP device--or am I missing it?

To be fair, it's not clear to me how to get that information from the underlying API (https://learn.microsoft.com/en-us/windows/win32/wpd_sdk/retrieving-properties-for-a-single-object) but I'm new to MTP so I'm probably missing that too.

Any advice?  Thanks!

**Comment by tlokovic** [comment]
Ah, my bad, now I see Object::get_object_properties (https://github.com/daladim/winmtp/blob/master/src/object/mod.rs#L68C109-L68C130), so if I just dig through the resulting ‎IPortableDeviceValues I suspect I'll find what I need.

If that's correct, please feel free to close this issue.  Sorry for the noise.

**Comment by daladim** [comment]
Hello, yes I think `get_object_properties` is indeed what you're looking for.

Note that this is a very recent addition to this lib, and it has not been released to crates.io yet. I'll try to release version 0.2.2 tonight. In the meantime, you can always use `[patches.crates-io]` in your `Cargo.toml` to fetch winmtp from Github

**Comment by daladim** [comment]
winmtp 0.3.0 has just been released!
You can now easily get file sizes using e.g. https://github.com/daladim/winmtp/blob/4f9b9e83b7616f524883a6fe95f91ada7ae0be6b/tests/file_access.rs#L112

I haven't dug into file dates. I may be wrong, but I suppose you'll have to query an int that happens to be a [`FILETIME`](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime)
