### ISSUE TITLE
关于从MTP设备拷贝文件到PC端

### ISSUE THREAD

**Issue by xuyuxuan** [daladim/winmtp#3]
目前是没有这个MTP设备拷贝文件到PC端吧 是不是可以加一个

**Comment by xuyuxuan** [comment]
试着这样实现，目前是报错
//将MTP 文件 添加PC端
    pub fn pull_file_from_mtp(
        basic_device: &BasicDevice,
        mtp_file_id: &str,
        local_file_path: &Path,
    ) -> Result<(), std::io::Error> {
        // 打开MTP设备上文件的读取流

        let app_ident = winmtp::make_current_app_identifiers!();
        let device = basic_device.open(&app_ident, true)?;
        let u16_cstring =
            U16CString::from_str(&mtp_file_id).expect("Failed to convert to U16CString");
        // 显示处理错误
        let object = match device.content()?.object_by_id(u16_cstring) {
            Ok(obj) => obj,
            Err(err) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!("Failed to retrieve MTP object: {}", err),
                ))
            }
        };
        // 显示处理错误
        let mut input_stream = match object.open_read_stream() {
            Ok(stream) => stream,
            Err(err) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!("Failed to open read stream: {}", err),
                ))
            }
        };

        let mut output_file = File::create(local_file_path)?;

        let mut buffer = [0u8; 4096];
        loop {
            let mut bytes_read = input_stream.read(&mut buffer)?;
            if bytes_read == 0 {
                break;
            }
            output_file.write_all(&buffer[..bytes_read])?;
        }

        Ok(())
    }

**Comment by daladim** [comment]
Hello, from what I understood using Google translate, you may want to have a look at this: https://github.com/daladim/winmtp/blob/master/tests/file_access.rs#L107

Cheers

**Comment by daladim** [comment]
After a quick look at your solution, I don't see anything obviously wrong, but please give me details about your error if you want helpful replies :)

**Comment by xuyuxuan** [comment]
> Hello, from what I understood using Google translate, you may want to have a look at this: https://github.com/daladim/winmtp/blob/master/tests/file_access.rs#L107
> 
> Cheers



> After a quick look at your solution, I don't see anything obviously wrong, but please give me details about your error if you want helpful replies :)
的确如此，代码没有问题，不过还是需要感谢你，是传参将文件id和文件夹id搞错了，导致的错误

**Comment by daladim** [comment]
Happy that I could help.
Happy programming with winmtp!
